#!/usr/bin/env bash

# Copyright (c) 2016 Cinchapi Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Run ./gradle spotlessApply to clean up the java code
./gradlew spotlessApply
diffs=`git diff-index --name-only HEAD --`
if [ -n "$diffs" ]; then
    git commit -m "[PRE-PUSH]: Code cleaned by Spotless Plugin"
    exit $?
else
    exit 0
fi
