#!/usr/bin/env bash
# Copyright (c) 2013-2017 Cinchapi Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "Checking for proper code formatting..."
./gradlew -Djenkins=true spotlessCheck

STATUS=$?
if [ $STATUS != 0 ]; then
  bold=$(tput bold)
  normal=$(tput sgr0)
  red=$(tput setaf 1)
  echo
  echo "${bold}${red}Please run ./gradlew spotlessApply to fix this error${normal}"
fi

exit $STATUS
