/*
 * Copyright (c) 2013-2019 Cinchapi Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.cinchapi.concourse.thrift.exceptions.messages;

import javax.annotation.Generated;

import com.cinchapi.concourse.thrift.exceptions.GenericMessageException;

@SuppressWarnings({ "cast", "rawtypes", "serial", "unchecked", "unused" })
/**
 * Thrown when a user attempts an operation for which she has insufficient
 * permission.
 */
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2018-05-26")
public class PermissionException extends GenericMessageException {
    private static String description = "Thrown when a user attempts an operation for which she has "
            + "insufficient permission.";

    public PermissionException() {
        super();
    }

    public PermissionException(String message) {
        super(message);
    }

    public PermissionException(GenericMessageException other) {
        super(other);
    }
}
