#!/usr/bin/env bash

# Copyright (c) 2013-2017 Cinchapi Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Get the PID for the running Mockcourse processes. Some programming languages
# aren't smart enough to fork processes and keep track of their PIDs, so in
# those cases, this is the script to use

# Ensure the script operates from the project root directory
cd "${0%/*}"

ps ax | grep GroovyStarter | grep -v '00 grep' | sed 's/^[ \t]*//' | cut -f 1 -d ' '
