#!/usr/bin/env bash

# Copyright (c) 2013-2017 Cinchapi Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Ensure the script operates from the project root directory
cd "${0%/*}"

LIBDIR="../concourse-driver-java/build/libs"
if [ ! -d "$LIBDIR" ]; then
  cd ../concourse-driver-java
  ../gradlew build
  cd - > /dev/null
fi

# Execute the groovy command
groovy -cp "$LIBDIR/*" src/main/groovy/com/cinchapi/mockcourse/Mockcourse.groovy "$@"
