#!/usr/bin/env bash

# Copyright (c) 2013-2017 Cinchapi Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Wrapper for the Python Invoke script (http://pyinvoke.org)

# Ensure the script operates from the project root directory
cd "${0%/*}"

# Run initialization if it was not done previously
INIT_SCRIPT="`dirname $0`"/init-repo.sh
if [ -x $INIT_SCRIPT ]; then
    echo "Initializing..."
    bash $INIT_SCRIPT
fi

invoke "$@"
