# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "geerlingguy/centos6"
  #https://github.com/mitchellh/vagrant/issues/5186 provided solution to solve this pub/private key issue.
  config.ssh.insert_key = false

  # The entire concourse repository is shared with the Vagrant VM.
  config.vm.synced_folder "../../", "/code"

  # Run the following actions after the VM is provisioned to ensure that we
  # can do everything we need to do
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum -y install java-1.8.0-openjdk-devel
    sudo yum -y install git
    sudo yum -y install zip
    sudo yum -y install unzip
    gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
    curl -sSL https://get.rvm.io | bash -s stable
    source /etc/profile.d/rvm.sh
  SHELL

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
    config.vm.provider "virtualbox" do |vb|
  # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  
  # Customize the amount of memory on the VM:
    vb.memory = "1024"
    end
  #
  # View the documentation for the provider you are using for more
  # information on available options.
end
