/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.cinchapi.concourse.thrift;

/**
 * A representation for an enum that declares the type of a TSymbol.
 */
public enum TSymbolType implements org.apache.thrift.TEnum {
  CONJUNCTION(1),
  KEY(2),
  VALUE(3),
  PARENTHESIS(4),
  OPERATOR(5);

  private final int value;

  private TSymbolType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TSymbolType findByValue(int value) { 
    switch (value) {
      case 1:
        return CONJUNCTION;
      case 2:
        return KEY;
      case 3:
        return VALUE;
      case 4:
        return PARENTHESIS;
      case 5:
          return OPERATOR;
      default:
        return null;
    }
  }
}
