#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

VERSION = %q"0.5.0"

NULL = ::TObject.new({
  %q"type" =>   9,
})

JSON_RESERVED_IDENTIFIER_NAME = %q"$id$"
