#!/usr/bin/env bash

###############################################
### 		Concourse Script for Unix 		###
###############################################

usage(){
	echo "Usage: $0 { start | stop | dump | help }"
	exit -1
}

# Set APP_HOME to the parent directory
APP_HOME="`pwd -P`/.."
cd $APP_HOME

# Store PID in APP_HOME
PID="$APP_HOME/concourse.pid"

# Find JAVA command
JAVA="/usr/bin/java"

# Set VM Options
#VM_OPTS=""


# Set CLASSPATH
CLASSPATH="$APP_HOME/lib/*"

# Run operation
case $1 in
	help )
		usage
		;;
	stop )
		if [ ! -f $PID ]; then
    		echo "Concourse Server is not currently running..."
    	else
    		exec $JAVA -classpath "$CLASSPATH" org.cinchapi.concourse.server.ShutdownRunner "$@" &
			rm $PID
		fi
		exit 0
		;;
	* )
		if [ ! -f $PID ]; then
    		exec $JAVA $VM_OPTS -classpath "$CLASSPATH" org.cinchapi.concourse.server.ConcourseServer "$@" &
			echo $! > $PID
    	else
    		echo "Concourse server is already running..."
		fi
		exit 0
		;;
esac