#!/usr/bin/env bash

###############################################
### 		Concourse Script for Unix 		###
###############################################

usage(){
	echo "Usage: $0 { start | status | stop | dump | help }"
	exit -1
}

status(){
	if [ ! -f $PID ]; then
		echo "Concourse Server is NOT currently running..."
	else
		PROC=$(cat $PID)
		echo "Concourse server is currently running (PID: $PROC)"
	fi
	exit 0
}

# Set APP_HOME to the parent directory
APP_HOME="`pwd -P`/.."
cd $APP_HOME

# Store PID in APP_HOME
PID="$APP_HOME/concourse.pid"

# Find JAVA command
JAVA="/usr/bin/java"

# Set VM Options
VM_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"


# Set CLASSPATH
CLASSPATH="$APP_HOME/lib/*"

# Run operation
case $1 in
	help )
		usage
		;;
	status )
		status
		;;
	stop )
		if [ ! -f $PID ]; then
    		status
    	else
    		exec $JAVA -classpath "$CLASSPATH" org.cinchapi.concourse.server.ShutdownRunner "$@" >> /dev/null >> /dev/null &
			rm $PID
			echo "Stopping Concourse server. Check the log for more details..."
		fi
		exit 0
		;;
	* )
		if [ ! -f $PID ]; then
    		exec nohup $JAVA $VM_OPTS -classpath "$CLASSPATH" org.cinchapi.concourse.server.ConcourseServer "$@" >> /dev/null >> /dev/null &
			echo $! > $PID
			echo "Starting Concourse server. Check the log for more details..."
    	else
    		status
		fi
		exit 0
		;;
esac