#!/usr/bin/env bash

###############################################
### 		Concourse Script for Unix 		###
###############################################

usage(){
	echo "Usage: $0 { start | stop | dump | help }"
	exit -1
}

# Set APP_HOME to the parent directory
APP_HOME="`pwd -P`/.."
cd $APP_HOME

# Find JAVA command
JAVA="/usr/bin/java"

# Set VM Options
#VM_OPTS=""


# Set CLASSPATH
CLASSPATH="$APP_HOME/lib/*"

# Run operation
case $1 in
	help )
		usage
		;;
	stop )
		exec $JAVA -classpath "$CLASSPATH" org.cinchapi.concourse.server.ShutdownRunner "$@"
		exit 0
		;;
	* )
		exec $JAVA $VM_OPTS -classpath "$CLASSPATH" org.cinchapi.concourse.server.ConcourseServer "$@"
		exit 0
		;;
esac