#
# Autogenerated by Thrift Compiler (0.9.3)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'concourse/thrift/data_types'
require 'concourse/thrift/shared_types'
require 'concourse/exceptions_types'
require 'concourse/thrift/complex_types'


module Concourse
  module Thrift
  end
end
