#
# Autogenerated by Thrift Compiler (0.12.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'concourse/thrift/concourse_types'

module Concourse
  module Thrift
    VERSION = %q"0.10.0"

    NULL = ::Concourse::Thrift::TObject.new({
      %q"type" =>       9,
    })

    JSON_RESERVED_IDENTIFIER_NAME = %q"$id$"

  end
end
