#!/usr/bin/env bash
#?Manage Concourse Server configuration.

# Copyright (c) 2013-2022 Cinchapi Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This config will setup all the enviornment variables and check that
# pthats are proper
. "`dirname "$0"`/.env"

# Specify the fully qualified name of the java CLI class to run.
PACKAGE="com.cinchapi"
CLI="configctl.lib.ConfigCli"

# The config files in order of lowest to highest priority
FILES=(
  concourse.prefs
  concourse.prefs.dev
)
ARGS=""
for file in "${FILES[@]}"; do
  ARGS=$ARGS"-f $APP_HOME/conf/$file "
done
ARGS=$(echo $ARGS | xargs)

# run the program
exec $JAVACMD -classpath "$CLASSPATH" -Dcom.cinchapi.lib.cli.reflectionScannerPackagePrefix=$PACKAGE com.cinchapi.lib.cli.HierarchicalCommandLineInterfaceRunner $PACKAGE.$CLI "$@" $ARGS