#!/usr/bin/env bash
#?Dump data from storage blocks for debugging purposes.

# This config will setup all the enviornment variables and check that
# pthats are proper
. "`dirname "$0"`/.env"

# run the program
exec $JAVACMD -classpath "$CLASSPATH" org.cinchapi.concourse.server.cli.DumpToolCli "$@"
