#!/usr/bin/env bash
#?Uninstall Concourse Server

# Copyright (c) 2013-2017 Cinchapi Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This config will setup all the enviornment variables and check that
# paths are proper
. "`dirname "$0"`/.env"

# Make sure that Concourse Server is not running, if it is refuse to uninstall
# because doing so would be very unsafe
STATUS=`bash $APP_HOME/bin/concourse status`
if [[ $STATUS == "Concourse Server is running PID:"* ]]; then
  die "ERROR: Cannot uninstall Concourse Server while it is running. Please stop the server and re-run this script."
fi

warn "
You have chosen to uninstall Concourse Server. This script will DELETE the binaries and source code while leaving all data and log files in their current locations.
"

# Files that may have been placed in a path accessible location
PATHFILES=(
  '/usr/local/bin/concourse'
  '/usr/local/bin/cash'
)

# Go to the APP_HOME
cd $APP_HOME
sudo -K # clear the sudo creds cache, so user is forced to type in password

# Check each of the $PATHFILES to see if it points to this server installation, if so, delete it
HOME=$(cd $APP_HOME; pwd -P)
for FILE in ${PATHFILES[@]}; do
  if [ -f $FILE ]; then
    DEST=`sed -n 17p $FILE | cut -d ' ' -f 4`
    DEST=`dirname $DEST`
    DEST=`dirname $DEST`
    if [ $DEST -ef $HOME ]; then
      echo "Removing $FILE from \$PATH..."
      sudo rm -rf $FILE
    fi
  fi
done

# Remove the service file, if necessary
if is_linux; then
    service="/etc/init.d/concourse"
    if [ -e $service ]; then
        sudo rm $service
    fi
fi

echo "Removing the installation directory at $HOME..."
CWD=`basename $HOME`
cd ..; rm -rf -- $CWD

echo
echo -e "${TEXT_COLOR_YELLOW}Concourse Server has been uninstalled.${TEXT_COLOR_RESET}"


exit 0
