#!/usr/bin/env bash
#?Manager user accounts.

# This config will setup all the enviornment variables and check that
# pthats are proper
. "`dirname "$0"`/.env"

# run the program
exec $JAVACMD -classpath "$CLASSPATH" org.cinchapi.concourse.server.cli.ManageUsersCli "$@"
