/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * 
 * @generated
 */
package com.cinchapi.concourse.thrift;

/**
 * When re-constructing the state of a record/field/index from some base state,
 * A {@link Diff} describes the {@link Action} necessary to perform using the
 * data from a {@link Write}.
 * 
 * @author dubex
 */
public enum Diff implements org.apache.thrift.TEnum {
    ADDED(1), REMOVED(2);

    private final int value;

    private Diff(int value) {
        this.value = value;
    }

    /**
     * Get the integer value of this enum value, as defined in the Thrift IDL.
     */
    public int getValue() {
        return value;
    }

    /**
     * Find a the enum type by its integer value, as defined in the Thrift IDL.
     * 
     * @return null if the value is not found.
     */
    public static Diff findByValue(int value) {
        switch (value) {
        case 1:
            return ADDED;
        case 2:
            return REMOVED;
        default:
            return null;
        }
    }
}
