#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *

VERSION = "0.5.0"
NULL = concourse.thriftapi.data.ttypes.TObject(**{
  "type" :   9,
})
JSON_RESERVED_IDENTIFIER_NAME = "$id$"
