#
# Autogenerated by Thrift Compiler (0.9.3)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from .data.ttypes import TObject

VERSION = "0.5.0"
NULL = TObject(**{
  "type" :   9,
})
JSON_RESERVED_IDENTIFIER_NAME = "$id$"
