<?php
namespace thrift;

/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


final class Constant extends \Thrift\Type\TConstant {
  static protected $VERSION;
  static protected $NULL;
  static protected $JSON_RESERVED_IDENTIFIER_NAME;

  static protected function init_VERSION() {
    return "0.5.0";
  }

  static protected function init_NULL() {
    return new \thrift\data\TObject(array(
      "type" =>       9,
    ));
  }

  static protected function init_JSON_RESERVED_IDENTIFIER_NAME() {
    return "\$id\$";
  }
}


