//
// Autogenerated by Thrift Compiler (0.12.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

const thrift = require('thrift');
const Thrift = thrift.Thrift;

const data_ttypes = require('./data_types');
const shared_ttypes = require('./shared_types');
const exceptions_ttypes = require('./exceptions_types');
const complex_ttypes = require('./complex_types');


const ttypes = module.exports = {};
ttypes.VERSION = '0.10.0';
ttypes.NULL = new data_ttypes.TObject({
  'data' : Buffer.alloc(0),
  'type' : 9
});
ttypes.JSON_RESERVED_IDENTIFIER_NAME = '$id$';
